## Preparing Tree Data

In [1]:
# imports
import pandas as pd

In [5]:
# read in data
df_abundance = pd.read_csv('bac_abundance.csv')
metadata = pd.read_csv("samp_metadata.csv")

In [6]:
# replace unknown family with genus
for i, row in enumerate(df_abundance.itertuples()):
    if row.Family == "Unknown_Family":
        df_abundance.at[i, "Family"] = row.Genus

In [7]:
df_abundance.drop(columns=['Unnamed: 0'], inplace=True)
df_phylum = df_abundance.groupby('Phylum').sum()
# remove columns that is not start with "Samp"
df_phylum = df_phylum[df_phylum.columns[df_phylum.columns.str.startswith('Samp')]]
df_phylum.head()

,Samp001,Samp002,Samp003,Samp004,Samp005,Samp006,Samp007,Samp008,Samp009,Samp010,...,Samp231,Samp232,Samp233,Samp234,Samp235,Samp236,Samp237,Samp238,Samp239,Samp240
Family,,,,,,,,,,,,,,,,,,,,,
01D2Z36,1,0,0,0,0,0,0,0,2,0,...,17,1,6,3,4,7,4,5,1,5
0319-6G20,4,0,4,5,4,0,10,3,3,8,...,15,10,19,8,20,30,18,16,28,27
053A03-B-DI-P58,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
27F-1492R,0,0,1,0,0,0,1,1,0,0,...,0,0,0,3,1,6,1,1,3,1
37-13,4,0,3,2,0,2,6,3,0,7,...,15,8,20,8,9,20,6,28,11,15

In [10]:
# all families
all_phylum = df_phylum.index
all_phylum

Index(['01D2Z36', '0319-6G20', '053A03-B-DI-P58', '27F-1492R', '37-13',
       '67-14', 'A0839', 'A21b', 'A4b', 'AB1',
       ...
       'Weeksellaceae', 'Xanthobacteraceae', 'Xanthomonadaceae',
       'Xiphinematobacteraceae', 'bac2nit3', 'bacteriap25', 'cvE6',
       'env.OPS_17', 'mle1-27', 'possible_family_01'],
      dtype='object', name='Family', length=305)

In [11]:
with open("phylum.txt", "w") as f:
    for family in all_phylum:
        f.write(family + "\n")